services:
  app:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    volumes:
      - ./src/:/go/src/app
    tty: true
    environment:
      - SPREAD_SHEETS_ID=${SPREAD_SHEETS_ID}
      - WORKSHEET_NAME=${WORKSHEET_NAME}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}