FROM golang:1.22-alpine

# ディレクトリ指定
ENV ROOT=/go/src/app
WORKDIR ${ROOT}

# # Git インストール
# RUN apk update && apk add git
# # ファイルコピー
# COPY ./main.go ${ROOT}
# COPY ./go.mod ${ROOT}

# RUN go mod tidy \
# && go install github.com/cosmtrek/air@latest

# CMD ["air"]